import { z } from 'zod';

import { RunStageSchema } from './task-loop-state';

export const EvidenceKindSchema = z.enum([
  'requirement_freeze',
  'architecture_freeze',
  'task_graph',
  'planning_request',
  'planning_conversation_link',
  'planning_finalize_attempt',
  'planning_finalize_recovery',
  'planning_materialized_result',
  'planning_sufficiency_decision',
  'planning_model_routing_decision',
  'planning_proof_report',
  'task_note',
  'test_report',
  'review_note',
  'bridge_markdown',
  'bridge_structured_review',
  'gate_result',
  'execution_request',
  'execution_result',
  'review_request',
  'review_result',
  'patch',
  'command_log',
  'build_log',
  'review_input',
  'review_output',
  'workspace_runtime',
  'job_record',
  'queue_state',
  'retry_decision',
  'recovery_summary',
  'release_review_request',
  'release_review_result',
  'release_markdown',
  'release_structured_review',
  'run_acceptance',
  'daemon_state',
  'worker_record',
  'worker_lease',
  'heartbeat',
  'concurrency_decision',
  'cancellation_request',
  'cancellation_result',
  'stale_job_reclaim',
  'drain_summary',
  'runtime_metrics',
  'process_handle',
  'runner_lifecycle',
  'workspace_lifecycle',
  'workspace_cleanup',
  'workspace_gc',
  'scheduling_decision',
  'quota_decision',
  'failure_record',
  'job_disposition',
  'runtime_daemon_startup',
  'runtime_daemon_shutdown',
  'e2e_validation_report',
  'bridge_drift_incident',
  'bridge_recovery_attempt',
  'bridge_health',
  'runner_resume_state',
  'rollback_record',
  'debug_snapshot',
  'remediation_proposal',
  'remediation_result',
  'self_repair_policy_decision',
  'stability_report',
]);

export type EvidenceKind = z.infer<typeof EvidenceKindSchema>;

export const EvidenceManifestSchema = z.object({
  evidenceId: z.string().uuid(),
  runId: z.string().uuid(),
  taskId: z.string().uuid().optional(),
  stage: RunStageSchema,
  kind: EvidenceKindSchema,
  timestamp: z.string().datetime(),
  producer: z.string().min(1),
  artifactPaths: z.array(z.string().min(1)).min(1),
  summary: z.string().min(1),
  metadata: z.record(z.unknown()).default({}),
});

export type EvidenceManifest = z.infer<typeof EvidenceManifestSchema>;
