import { randomUUID } from 'node:crypto';

import {
  ExecutionArtifactSchema,
  ExecutionResultSchema,
  ExecutorCapabilitySchema,
  type ExecutionArtifact,
  type ExecutionRequest,
  type ExecutionResult,
  type ExecutorCapability,
  type TestResult,
} from '../contracts';
import { createEmptyPatchSummary, parsePatchSummary } from '../utils/patch-parser';
import type { ExecutionExecutor } from './executor-registry';
import {
  CodexExecutionPayloadBuilder,
  type CodexExecutionPayload,
} from './codex-execution-payload-builder';

export type CodexRunnerResponse = {
  status: ExecutionResult['status'];
  summary: string;
  stdout?: string | undefined;
  stderr?: string | undefined;
  exitCode?: number | null | undefined;
  patch?: string | undefined;
  testResults?: readonly TestResult[] | undefined;
  artifacts?: readonly Omit<ExecutionArtifact, 'artifactId'>[] | undefined;
  metadata?: Record<string, unknown> | undefined;
  startedAt?: string | undefined;
  finishedAt?: string | undefined;
};

export interface CodexRunner {
  run(payload: CodexExecutionPayload): Promise<CodexRunnerResponse>;
}

export class StubCodexRunner implements CodexRunner {
  public run(payload: CodexExecutionPayload): Promise<CodexRunnerResponse> {
    void payload;
    const timestamp = new Date().toISOString();
    return Promise.resolve({
      status: 'failed',
      summary: 'Codex runner is not configured in this local skeleton.',
      stdout: '',
      stderr: 'Configure a concrete Codex runner before using the codex executor in production.',
      exitCode: 78,
      startedAt: timestamp,
      finishedAt: timestamp,
      testResults: [],
      artifacts: [],
      metadata: {
        stubbed: true,
      },
    });
  }
}

export class CodexExecutor implements ExecutionExecutor {
  public readonly type = 'codex' as const;

  public constructor(
    private readonly runner: CodexRunner = new StubCodexRunner(),
    private readonly payloadBuilder: CodexExecutionPayloadBuilder = new CodexExecutionPayloadBuilder(),
  ) {}

  public getCapability(): ExecutorCapability {
    return ExecutorCapabilitySchema.parse({
      type: this.type,
      description:
        'Structured Codex execution adapter that can later target a real CLI, API, or cloud runtime.',
      supportsPatchOutput: true,
      supportsTestResults: true,
      supportsStructuredPrompt: true,
      supportsWorkspaceCommands: false,
    });
  }

  public async execute(request: ExecutionRequest): Promise<ExecutionResult> {
    const payload = this.payloadBuilder.build(request);
    const inputArtifact = ExecutionArtifactSchema.parse({
      artifactId: randomUUID(),
      kind: 'review-input',
      label: 'codex-execution-payload',
      content: payload.prompt,
      metadata: {
        executorType: this.type,
      },
    });

    try {
      const response = await this.runner.run(payload);
      const patchSummary = response.patch
        ? parsePatchSummary(response.patch, {
            notes: ['Patch generated by Codex runner.'],
          })
        : createEmptyPatchSummary(['Codex runner did not return a patch.']);
      const artifacts = [
        inputArtifact,
        ...(response.patch
          ? [
              ExecutionArtifactSchema.parse({
                artifactId: randomUUID(),
                kind: 'patch',
                label: 'codex-patch',
                content: response.patch,
                metadata: {
                  executorType: this.type,
                },
              }),
            ]
          : []),
        ...this.normalizeArtifacts(response.artifacts ?? []),
      ];

      return ExecutionResultSchema.parse({
        executionId: request.executionId,
        runId: request.runId,
        taskId: request.taskId,
        executorType: this.type,
        status: response.status,
        startedAt: response.startedAt ?? new Date().toISOString(),
        finishedAt: response.finishedAt ?? new Date().toISOString(),
        summary: response.summary,
        patchSummary,
        testResults: response.testResults ?? [],
        artifacts,
        stdout: response.stdout ?? '',
        stderr: response.stderr ?? '',
        exitCode: response.exitCode ?? null,
        metadata: response.metadata ?? {},
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Unknown Codex runner failure';
      const timestamp = new Date().toISOString();

      return ExecutionResultSchema.parse({
        executionId: request.executionId,
        runId: request.runId,
        taskId: request.taskId,
        executorType: this.type,
        status: 'failed',
        startedAt: timestamp,
        finishedAt: timestamp,
        summary: 'Codex execution failed before producing a structured result.',
        patchSummary: createEmptyPatchSummary(['Codex runner threw before producing a patch.']),
        testResults: [],
        artifacts: [inputArtifact],
        stdout: '',
        stderr: message,
        exitCode: 1,
        metadata: {
          runnerError: true,
        },
      });
    }
  }

  private normalizeArtifacts(
    artifacts: readonly Omit<ExecutionArtifact, 'artifactId'>[],
  ): ExecutionArtifact[] {
    return artifacts.map((artifact) =>
      ExecutionArtifactSchema.parse({
        artifactId: randomUUID(),
        ...artifact,
      }),
    );
  }
}
